<a href="https://colab.research.google.com/github/yujie166/phythons/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.array([1, 2, 3])
x
array([1,2, 3])
y = np.arange(10)  # 類似 Python 的 range, 但是回傳 array
y
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([1, 2, 3, 6])
b = np.linspace(0, 2, 4)  # 建立一個array, 在0與2的範圍之間讓4個點3等分
c = a - b
c
array([ 1.   ,  1.33333333,  1.66666667,  4.        ])
a**2
array([ 1,  4,  9, 36])

In [ ]:
a = np.linspace(-np.pi, np.pi, 100)
b = np.sin(a)
c = np.cos(a)

In [ ]:
from numpy.random import rand
from numpy.linalg import solve, inv
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])
a.transpose()
array([[ 1. ,  3. ,  5. ],
       [ 2. ,  4. ,  9. ],
       [ 3. ,  6.7,  5. ]])
inv(a)
array([[-2.27683616,  0.96045198,  0.07909605],
       [ 1.04519774, -0.56497175,  0.1299435 ],
       [ 0.39548023,  0.05649718, -0.11299435]])
b =  np.array([3, 2, 1])
solve(a, b)  # 解方程式 ax = b
array([-4.83050847,  2.13559322,  1.18644068])
c = rand(3, 3)  # 建立一個 3x3 隨機矩陣
c
array([[  3.98732789,   2.47702609,   4.71167924],
       [  9.24410671,   5.5240412 ,  10.6468792 ],
       [ 10.38136661,   8.44968437,  15.17639591]])
np.dot(a, c)  # 矩陣相乘
array([[  53.61964114,   38.8741616 ,   71.53462537],
       [ 118.4935668 ,   86.14012835,  158.40440712],
       [ 155.04043289,  104.3499231 ,  195.26228855]])